[package]
name = "unm_server"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
thiserror = "1.0"
regex = "1.x"
log = "0.4"
log4rs = {version = "1.0", features = ["json_encoder", "file_appender", "console_appender"]}
#rocket = "0.5.0-rc.1"
openssl = "0.10.36"
md5 = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1.51"
http = "0.2"
futures = "0.3.17"
hyper = { version = "0.14", features = ["full"] }
reqwest = { version = "0.11", features = ["blocking", "json", "gzip", "deflate", "native-tls-vendored"] }
tokio = { version = "1", features = ["full"] }
hex = "0.4.3"
url = "2.2.2"
