[package]
edition = "2021"
name = "unm_resolver_napi"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.0.3", default-features = false, features = ["napi4"] }
napi-derive = "2.0.7"
unm_resolver = { path = "../unm_resolver" }

[build-dependencies]
napi-build = "1.2.1"
