[package]
name = "unm_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.10"
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
