[package]
name = "unm_crypto"
description = "The crypto toolkit for UnblockNeteaseMusic."
version = "0.1.0"
edition = "2021"
repository = "https://github.com/UnblockNeteaseMusic/server-rust"
readme = "../README.md"
license = "LGPL-3.0-only"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = { version = "0.10.40", features = ["vendored"] }

thiserror = "1.0.31"

serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"

regex = "1.5.5"
md5 = "0.7.0"
url = "2.2.2"
concat-string = "1.0.1"
faster-hex = "0.6.1"
base64 = "0.13.0"
smallvec = { version = "1.8.0", features = ["union", "const_generics", "const_new"] }
log = "0.4.17"
once_cell = "1.10.0"

[features]

