name: Check if the code can build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          default: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: v0-${{ runner.os }}-cargo-check-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            v0-${{ runner.os }}-cargo-check-${{ hashFiles('**/Cargo.lock') }}
            v0-${{ runner.os }}-cargo-check-
            v0-${{ runner.os }}-cargo-
      - uses: actions-rs/cargo@v1
        with:
          command: check

  cargo-test:
    needs: cargo-check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-11
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          default: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: v0-${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            v0-${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
            v0-${{ runner.os }}-cargo-test-
            v0-${{ runner.os }}-cargo-
#      - if: runner.os == 'Windows'
#        run: |
#          choco install openssl
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p unm_server
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p unm_macro
